configurable outgoing mailbox
sqlchat/sqlchat pull request #149
Opened 2024-02-06 06:06 UTC by lushenle

# 147 
supported to be configurable the outgoing mail

2024-02-06 06:13 UTC, tianzhou approved these changes
LGTM

2024-02-06 06:14 UTC, tianzhou requested changes

2024-02-06 06:14 UTC, tianzhou commented on src/pages/api/auth/[...nextauth].ts
> +          from: process.env.EMAIL_FROM,
Please include "noreply@sqlchat.ai" as the default if not specified anything

2024-02-07 03:15 UTC, lushenle commented on src/pages/api/auth/[...nextauth].ts
> +          from: process.env.EMAIL_FROM,
> Please include "[noreply@sqlchat.ai](mailto:noreply@sqlchat.ai)" as the default if not specified anything

我的失误，考虑不周了^_^

2024-02-07 03:16 UTC, tianzhou approved these changes
LGTM

2024-02-07 03:16 UTC, merged

2024-02-07 03:17 UTC, tianzhou commented
Thanks for the contribution