[WIP] feat: add table picker to choose a table to generate correct SQL statement
sqlchat/sqlchat pull request #74
Opened 2023-05-01 11:06 UTC by CorrectRoadH

👀 for resolving the https://github.com/sqlchat/sqlchat/issues/51. to add a picker to choose a table that the user wants to use is a simple solution.

But there are some problems that need to resolve🧑‍💻
- https://github.com/sqlchat/sqlchat/pull/54
- #58 
- #57
- #65
- #69
# Features:
- add loading status after chosen database
- only send the selected table struct as prompt
- send all table struct as prompt when "All table" is selected

## What will happen if chat or select another table when the database schema is loading yet
Sometimes we meet some databases with very many tables. the loading will be long👀(though it has already been optimized in #65, the time may be up to a few seconds. So two requests may append yet). 

So if we send a message when the database is loading yet? What will happen? 

Solution 1
If the undone request exists, cancel the current request.

Solution 2
If the undone request exists, cancel the old request.🤔 I think the solution is simple and has fewer mental burdens.  and there are two implementation methods:
- Axios cancel
- Promise race
- AbortController
ref: https://blog.csdn.net/weixin_48276895/article/details/129192752
ref: https://stackoverflow.com/questions/38329209/how-to-cancel-abort-ajax-request-in-axios

Solution 3
an additional judge after fetch schema data.

WIP
## What is next?
a picker of the table is a temporary solution for resolving #51. I think it is not good enough. When we want to generate statements from multiple tables. the select can't do it. I think a selection that can select multiple tables may be a good solution 🤔

2023-05-04 15:51 UTC, tianzhou requested changes

2023-05-04 15:51 UTC, tianzhou commented on src/components/ConnectionSidebar.tsx
> +    const newTable =
tableList

2023-05-05 04:51 UTC, CorrectRoadH commented
@tianzhou PTAL

2023-05-05 08:17 UTC, tianzhou requested changes

2023-05-05 08:17 UTC, tianzhou commented on src/components/ConnectionSidebar.tsx
> +                      onValueChange={(databaseName) =>
tableName

2023-05-05 08:17 UTC, tianzhou commented on src/components/ConnectionSidebar.tsx
> +        name: t("connection.all-tables"),
To make it less error prone.

this should be name: ""

and in the the rendering part if name == "" then display t("connection.all-tables")

2023-05-05 08:32 UTC, CorrectRoadH commented
@tianzhou  PTAL again🤩

2023-05-05 08:46 UTC, tianzhou approved these changes
LGTM

2023-05-05 08:46 UTC, merged